/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.14/samples
 */

plugins {
    id("java")
    id("war")
    id("org.gretty") version "4.0.3"
}

gretty {
    servletContainer = "tomcat11"
}

repositories {
    mavenCentral()
}

dependencies {
    // JSF API
    // https://mvnrepository.com/artifact/jakarta.faces/jakarta.faces-api
    implementation("jakarta.faces:jakarta.faces-api:4.1.2")

    // JUnit for testing
    // https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter-api
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.13.0-M1")
    // https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter-api
    runtimeOnly("org.junit.jupiter:junit-jupiter-api:5.13.0-M1")

    // JSF Specificaton
    // https://mvnrepository.com/artifact/com.sun.faces/jsf-impl
    implementation("com.sun.faces:jsf-impl:2.1.25")
}
